# netlify.toml

[build]
  command = "npm run build"
  publish = "Task01/frontend/build" # Publish directory for Task 1 frontend

[context.production]
  command = "npm run build"
  publish = "Task02/client/build" # Publish directory for Task 2 frontend