# netlify.toml

[build]
  command = "npm run build"
  publish = "/build" 
  base = "L3Task02/fullstack-project-management-tool-master/client"

[context.production]
  command = "npm run build"
  publish = "/build" 