# netlify.toml

[build]
  command = "npm run build"
  publish = "task1/frontend/build" # Publish directory for Task 1 frontend

[context.production]
  command = "npm run build"
  publish = "task2/client/build" # Publish directory for Task 2 frontend