# netlify.toml

[build]
  command = "npm run build"
  publish = "L3Task02/client/build" 
  base = "L3Task02/client"

[context.production]
  command = "npm run build"
  publish = "L3Task02/client/build" 